- hosts: all
  tasks:
    - name: Ensure local certs directory exists
      file: state=directory path=/usr/local/share/ca-certificates

    - name: Install certs
      ansible.builtin.copy:
        src: /home/ubuntu/ca-certificates/
        dest: /usr/local/share/ca-certificates/
        
    - name: Update cert index
      shell: /usr/sbin/update-ca-certificates
